apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rollout-realtimeapp
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: realtimeapp
  targetCPUUtilizationPercentage: 80