---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisapp
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      annotations:
        linkerd.io/inject: enabled 
    spec:
      containers:
      - name: redis
        image: redis:4-32bit
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379 # named port
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 5
        #  readinessProbe:
        #   exec:
        #     command:
        #     - redis-cli
        #     - ping
        #   initialDelaySeconds: 60
        #   # timeoutSeconds: 5
        #   periodSeconds: 60
        #   failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redisapp
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: realtimeapp
  labels:
    app: realtime   
spec:
  selector:
    matchLabels:
      app: realtime
  replicas: 1
  template:
    metadata:
      labels:
        app: realtime
      annotations:
        linkerd.io/inject: enabled 
    spec:
      containers:
      - name: realtimeapp
        # image: gbaeke/fluxapp:1.0.0
        image: gbaeke/fluxapp:1.0.2
        env:
        - name: REDISHOST
          value: "redisapp:6379"
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 5
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: realtimeapp-active
      previewService: realtimeapp-preview
      prePromotionAnalysis:
        templates:
        - templateName: realtime-analysis
        args:
        - name: service-name
          value: realtimeapp-preview.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeapp-active
  labels:
    app: realtime
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: realtime
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeapp-preview
  labels:
    app: realtime
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: realtime
---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: realtimeapp-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/affinity: cookie
#     nginx.ingress.kubernetes.io/affinity-mode: persistent
# spec:
#   rules:
#   - host: real.baeke.info
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: realtimeapp-active
#           servicePort: 80
